### ISSUE TITLE
Representative Mappings

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/gks-common#1]
As an informatician or analyst, in order to better understand GKS schemas and populate datasets correctly, it would be useful to have representative [Mappings](https://github.com/ga4gh/gks-common/blob/1b7e52d6013c6785300aa933efa9210e2aafa57b/schema/gks.common.yaml#L26) to common code systems [[SNOMED](https://en.wikipedia.org/wiki/SNOMED_CT), [LOINC](https://en.wikipedia.org/wiki/LOINC), [MONDO](https://mondo.monarchinitiative.org/)…]

**Comment by larrybabb** [comment]
I agree with that statement @bwalsh. We have added the `.mappings` attribute to the `DomainEntity` class which is a means by which you can relate common code systems and their identifiers to various domain concepts (i.e. Disease for MONDO and SNOMED). 
If this is not precisely what you are looking for, could you provide a clear example of a use case or two with example data?

**Comment by bwalsh** [comment]
Thanks @larrybabb - [this mapping](https://github.com/ga4gh/gks-common/blob/b8dfbb4be3d859085d9a4839346e96377706c3af/examples/domain-entities/gene.yaml#L10-L22) looks perfect.
