### ISSUE TITLE
Add a simple data type for dates

### ISSUE THREAD

**Issue by mbrush** [ga4gh/gks-common#3]
Can extend `string`, like `iri` and `code` data types do. 

Consider if we want `date` or `dateTime`.

See proposals from [Matt's](https://docs.google.com/document/d/1yL65lGqx_ZFIBOkUOy2Na79qRSIgS24D0Rvac6-wUHQ/edit#heading=h.1m0qlitj3u2) and [Bob's](https://docs.google.com/document/d/139qZu3xCBbsFKyk2JYeNZpl_WVImiwXaN-w2s8f6RTU/edit#heading=h.l0l8hrhmoilp) respective VA- and GA4GH- data type documents.

**Comment by larrybabb** [comment]
in json schema we are using the `format` attribute that is a sibling to the `type: string` declaration that allows us to control whether the particular property is a specific format of a date (time, date or datetime).

I suppose we could add something to the metaschema processor to maybe make the various data datatypes appear more cleanly, but I think we should defer that until there is a more urgent need. 

If this is primarily about the spec and it's documentation we can develop a way to generate these date-based datatypes in the documentation.

**Comment by larrybabb** [comment]
@ahwagner What say you about adding two simple/primitive datatypes in the spirit of `IRI` and `code` called `date` and `datetime` that simply predefine the `string` `format` so that it is more transparently represented in our documentation and  consistently applied in our models?

**Comment by ahwagner** [comment]
It's a good question and has me rethinking the decision around `IRI`; it might be simpler to just use the built-in type and format options. Same for `date` and `datetime`.

`code` is useful since it has a regex associated with it that I would only want to update in one place.

**Comment by larrybabb** [comment]
done
