### ISSUE TITLE
why was 'gks-common-source.yaml' renamed to 'core-im-source.yaml'?

### ISSUE THREAD

**Issue by mbrush** [ga4gh/gks-common#31]
@larrybabb it seems that as part of your refactoring of gks-commons yaml content, you changed the name of the main gks-commons-source file back to calling it 'core'.  

Recall we decided not to use the term 'core' in the gks-commons repo to avoid confusion with the core-im-source file in the va-spec repo.   We now have a situation where there is a "core-im-source.yaml" file in the gks-commons repo and in the va-spec repo, which represent different models/content.

Can we please rename this file back to 'gks-common-source.yaml'?

**Comment by larrybabb** [comment]
done in PR #35
