### ISSUE TITLE
Add a  'type' field to Entity?

### ISSUE THREAD

**Issue by mbrush** [ga4gh/gks-common#5]
Seems like the `type' property should be applicable to any Entity subtype? 

At present, it is added separately to most (but not all) subtypes of this class.  Was this by design?  If so, what is rationale? If not, can we move this property to live in the Entity class, rather than define separately to specific subclasses?

Related: In the [core-im-source yaml file](https://github.com/ga4gh/va-spec/blob/1.x/schema/va-spec/core-im/core-im-source.yaml), I noted that some classes have a `type` property with a hard coded value (e.g. "Document", "DataItem"), and others do not have a hard-coded type (e.g. "DataSet", "Statement") – by design, or should we fix/make consistent.  I will make a PR to add missing hard-coded types.

**Comment by larrybabb** [comment]
@ahwagner I think it is reasonable and pragmatic to move `type` to the top level `Entity` as a required field and remove any subclasses that should not have `type` (i.e. Mapping).

NOTE: currently `MappableEntity` does not have `type` but I believe it should.

**Comment by larrybabb** [comment]
PR #36
