### ISSUE TITLE
Should we move 'Expression' from vrs into gks-common?

### ISSUE THREAD

**Issue by mbrush** [ga4gh/gks-common#6]
If the notion of an `Expression` is not limited to variation (or perhaps even if it is) - does it make sense for this to live in gks-common rather than in the [vrs model](https://github.com/ga4gh/vrs/blob/2.x/schema/vrs/vrs-source.yaml)? 

If we move it, we should broaden its definition accordingly (e.g. to allow for expressions naming any type of entity, not just variants.

**Comment by larrybabb** [comment]
Since Cat-VRS and VRS both need this, we should move `Expression` to gks-common.

**Comment by larrybabb** [comment]
closed

**Comment by korikuzma** [comment]
This was done in #10
