### ISSUE TITLE
Clarify application of `Type` attribute throughout model

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/gks-common#7]
https://github.com/ga4gh/gks-common/blob/05ba1bffd042122aad01f3be0cca9c23ecd8549f/schema/gks-common/core-source.yaml#L94C7-L97C42

Why does `Extension` have a `type` attribute but nothing else does?  Let's clarify how we are applying the `type` attribute across GKS schemas for clarity.

**Comment by mbrush** [comment]
See also issue #5 - and comments therein.

**Comment by larrybabb** [comment]
The answer is 'No'. Since `Extension` does not inherit from `Entity`.  Only `Entity` subtypes are required to have a `type` field unless someone has an argument to present otherwise.
