### ISSUE TITLE
change all types to `date` and `datetime` on relevant attributes

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/gks-common#88]
https://github.com/ga4gh/gks-core/blob/d993cc68ddc637a2f3513da5e1043939bfd3393f/schema/gks-core/gks-core-source.yaml#L129

The primitive `date` and `datetime` types where added to gks-core and should be used in any attributes that they are relevant to.

**Comment by muhd360** [comment]
@larrybabb any issues a beginner can take up???

**Comment by larrybabb** [comment]
done
